#return:return.c
#	gcc $^ -o $@ -lpthread -O0

pthread_exit:pthread_exit.c
	gcc $^ -o $@ -lpthread -O0

#pthread_cancel:pthread_cancel.c
#	gcc $^ -o $@ -lpthread -O0
	

clean:
	rm return pthread_cancel pthread_exit
